# Generated by Django 2.1.2 on 2018-10-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20181027_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.TextField(default=''),
        ),
    ]
