# Generated by Django 2.1.2 on 2018-10-29 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_list',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='room',
            name='who_create',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
